title: AmbientGen
description: Building a text-to-ambient-sound generator with AudioLDM2
theme: jekyll-theme-minimal
baseurl: /ambientgen
github:
  owner_name: my-sonicase
  owner_url: https://github.com/my-sonicase
